name: dart_web_toolkit
version: 0.3.3
description: >
  Dart Web Toolkit (DWT) is a development toolkit for building and optimizing complex browser-based applications.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://www.dartwebtoolkit.com
dependencies:
  meta: ">=0.5.0"
  browser: ">=0.5.0"
  unittest: ">=0.5.0"
